crypto_lib.Crypto_DeriveKey.argtypes = [
    ctypes.c_void_p,
    ctypes.c_char_p,
    ctypes.POINTER(ctypes.c_ubyte),
    ctypes.c_int,
    ctypes.POINTER(ctypes.c_ubyte)
]
ecc_crypto_lib.Crypto_DeriveKey.restype = ctypes.c_int

class SecureVault:

    def derive_key_from_password(self, password):
        salt = os.urandom(16) 
        
        c_salt = (ctypes.c_ubyte * 16).from_buffer_copy(salt)
        c_key = (ctypes.c_ubyte * 32)()
        
        pass_bytes = password.encode('utf-8')

        success = ecc_crypto_lib.Crypto_DeriveKey(
            self.obj, 
            pass_bytes, 
            c_salt, 
            16, 
            c_key
        )

        if not success:
            raise Exception("Argon2id Failed")
            
        return bytes(c_key), salt

if __name__ == "__main__":
    vault = SecureVault()
    
    user_pass = "admin123_super_kuat"
    
    derived_key, salt_used = vault.derive_key_from_password(user_pass)
    print(f"Derived Key (Hex): {derived_key.hex()}")
    
    vault = SecureVault()

    user_secret = "This is a $1M company secret"
    print(f"Input: {user_secret}")
    try:
        result = vault.encrypt(user_secret)
        
        print("\n[C++ Core Result]")
        print(f"Ciphertext : {result['ciphertext']}")
        print(f"IV (Nonce) : {result['iv']}")
        print(f"Auth Tag   : {result['tag']}")
        print("\nIntegrity Check: Valid (Generated by OpenSSL/C++)")
        
    except Exception as e:
        print(f"Error: {e}")
    vault.close()

ecc_crypto_lib.Crypto_Generate_ECC.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_ubyte), ctypes.POINTER(ctypes.c_ubyte)]
ecc_crypto_lib.Crypto_Compute_ECDH.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_ubyte), ctypes.POINTER(ctypes.c_ubyte), ctypes.POINTER(ctypes.c_ubyte)]

class SecureVault:

    def hybrid_encrypt_ecc(self, data, server_public_key_bytes):
        my_pub = (ctypes.c_ubyte * 32)()
        my_priv = (ctypes.c_ubyte * 32)()
        ecc_crypto_lib.Crypto_Generate_ECC(self.obj, my_pub, my_priv)
        
        shared_secret = (ctypes.c_ubyte * 32)()
        c_server_pub = (ctypes.c_ubyte * 32).from_buffer_copy(server_public_key_bytes)
        
        ecc_crypto_lib.Crypto_Compute_ECDH(self.obj, my_priv, c_server_pub, shared_secret)
        
        wrapping_key = bytes(shared_secret)

        aes_data_key = os.urandom(32)
        
        return {
            "ephemeral_public_key": bytes(my_pub).hex(),
            "encrypted_aes_key": "...",
            "ciphertext": encrypted_packet['ciphertext'],
            "iv": encrypted_packet['iv'],
            "tag": encrypted_packet['tag']
        }