crypto_lib.Crypto_DeriveKey.argtypes = [
    ctypes.c_void_p,
    ctypes.c_char_p,
    ctypes.POINTER(ctypes.c_ubyte),
    ctypes.c_int,
    ctypes.POINTER(ctypes.c_ubyte)
]
rsa_crypto_lib.Crypto_DeriveKey.restype = ctypes.c_int

class SecureVault:

    def derive_key_from_password(self, password):
        salt = os.urandom(16) 
        
        c_salt = (ctypes.c_ubyte * 16).from_buffer_copy(salt)
        c_key = (ctypes.c_ubyte * 32)()
        
        pass_bytes = password.encode('utf-8')

        success = rsa_crypto_lib.Crypto_DeriveKey(
            self.obj, 
            pass_bytes, 
            c_salt, 
            16, 
            c_key
        )

        if not success:
            raise Exception("Argon2id Failed")
            
        return bytes(c_key), salt

if __name__ == "__main__":
    vault = SecureVault()
    
    user_pass = "admin123_super_kuat"
    
    derived_key, salt_used = vault.derive_key_from_password(user_pass)
    print(f"Derived Key (Hex): {derived_key.hex()}")
    
    vault = SecureVault()

    user_secret = "This is a $1M company secret"
    print(f"Input: {user_secret}")
    try:
        result = vault.encrypt(user_secret)
        
        print("\n[C++ Core Result]")
        print(f"Ciphertext : {result['ciphertext']}")
        print(f"IV (Nonce) : {result['iv']}")
        print(f"Auth Tag   : {result['tag']}")
        print("\nIntegrity Check: Valid (Generated by OpenSSL/C++)")
        
    except Exception as e:
        print(f"Error: {e}")
    vault.close()

    def hybrid_encrypt_send(self, data, server_public_key_pem):
        session_key = os.urandom(32) 
        
 _encrypt_with_key di wrapper C++)
        encrypted_data_packet = self.encrypt_aes_gcm(data, session_key)
        
        rsa_buffer = (ctypes.c_ubyte * 512)()
        c_session_key = (ctypes.c_ubyte * 32).from_buffer_copy(session_key)
        c_pub_key = ctypes.c_char_p(server_public_key_pem.encode('utf-8'))
        
        rsa_len = rsa_crypto_lib.Crypto_RSA_Wrap(
            self.obj,
            c_session_key,
            c_pub_key,
            rsa_buffer
        )
        
        if rsa_len < 0:
            raise Exception("RSA Wrapping Failed")
            
        encrypted_session_key = bytes(rsa_buffer[:rsa_len])
        
        del session_key 
        
        return {
            "enc_key": base64.b64encode(encrypted_session_key).decode(),
            "ciphertext": encrypted_data_packet['ciphertext'],
            "iv": encrypted_data_packet['iv'],
            "tag": encrypted_data_packet['tag']
        }